/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SocialWorkRouteImport } from './routes/social-work'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ResponsibilitiesRouteImport } from './routes/responsibilities'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MediaRouteImport } from './routes/media'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CampsRouteImport } from './routes/camps'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSkillsRouteImport } from './routes/admin/skills'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPublicationsRouteImport } from './routes/admin/publications'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminEducationRouteImport } from './routes/admin/education'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminCommunityRouteImport } from './routes/admin/community'
import { Route as AdminCertificatesRouteImport } from './routes/admin/certificates'
import { Route as AdminCampsRouteImport } from './routes/admin/camps'
import { Route as AdminAwardsRouteImport } from './routes/admin/awards'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialWorkRoute = SocialWorkRouteImport.update({
  id: '/social-work',
  path: '/social-work',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibilitiesRoute = ResponsibilitiesRouteImport.update({
  id: '/responsibilities',
  path: '/responsibilities',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublicationsRoute = AdminPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEducationRoute = AdminEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampsRoute = AdminCampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAwardsRoute = AdminAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/awards': typeof AwardsRoute
  '/camps': typeof CampsRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/responsibilities': typeof ResponsibilitiesRoute
  '/skills': typeof SkillsRoute
  '/social-work': typeof SocialWorkRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/camps': typeof AdminCampsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/awards': typeof AwardsRoute
  '/camps': typeof CampsRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/responsibilities': typeof ResponsibilitiesRoute
  '/skills': typeof SkillsRoute
  '/social-work': typeof SocialWorkRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/camps': typeof AdminCampsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/awards': typeof AwardsRoute
  '/camps': typeof CampsRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/media': typeof MediaRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/responsibilities': typeof ResponsibilitiesRoute
  '/skills': typeof SkillsRoute
  '/social-work': typeof SocialWorkRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/camps': typeof AdminCampsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/awards'
    | '/camps'
    | '/certificates'
    | '/contact'
    | '/education'
    | '/events'
    | '/gallery'
    | '/journey'
    | '/media'
    | '/privacy'
    | '/publications'
    | '/responsibilities'
    | '/skills'
    | '/social-work'
    | '/terms'
    | '/timeline'
    | '/admin/awards'
    | '/admin/camps'
    | '/admin/certificates'
    | '/admin/community'
    | '/admin/content'
    | '/admin/education'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/media'
    | '/admin/publications'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/awards'
    | '/camps'
    | '/certificates'
    | '/contact'
    | '/education'
    | '/events'
    | '/gallery'
    | '/journey'
    | '/media'
    | '/privacy'
    | '/publications'
    | '/responsibilities'
    | '/skills'
    | '/social-work'
    | '/terms'
    | '/timeline'
    | '/admin/awards'
    | '/admin/camps'
    | '/admin/certificates'
    | '/admin/community'
    | '/admin/content'
    | '/admin/education'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/media'
    | '/admin/publications'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/awards'
    | '/camps'
    | '/certificates'
    | '/contact'
    | '/education'
    | '/events'
    | '/gallery'
    | '/journey'
    | '/media'
    | '/privacy'
    | '/publications'
    | '/responsibilities'
    | '/skills'
    | '/social-work'
    | '/terms'
    | '/timeline'
    | '/admin/awards'
    | '/admin/camps'
    | '/admin/certificates'
    | '/admin/community'
    | '/admin/content'
    | '/admin/education'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/media'
    | '/admin/publications'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AwardsRoute: typeof AwardsRoute
  CampsRoute: typeof CampsRoute
  CertificatesRoute: typeof CertificatesRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  JourneyRoute: typeof JourneyRoute
  MediaRoute: typeof MediaRoute
  PrivacyRoute: typeof PrivacyRoute
  PublicationsRoute: typeof PublicationsRoute
  ResponsibilitiesRoute: typeof ResponsibilitiesRoute
  SkillsRoute: typeof SkillsRoute
  SocialWorkRoute: typeof SocialWorkRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-work': {
      id: '/social-work'
      path: '/social-work'
      fullPath: '/social-work'
      preLoaderRoute: typeof SocialWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsibilities': {
      id: '/responsibilities'
      path: '/responsibilities'
      fullPath: '/responsibilities'
      preLoaderRoute: typeof ResponsibilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps': {
      id: '/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publications': {
      id: '/admin/publications'
      path: '/publications'
      fullPath: '/admin/publications'
      preLoaderRoute: typeof AdminPublicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/education': {
      id: '/admin/education'
      path: '/education'
      fullPath: '/admin/education'
      preLoaderRoute: typeof AdminEducationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/camps': {
      id: '/admin/camps'
      path: '/camps'
      fullPath: '/admin/camps'
      preLoaderRoute: typeof AdminCampsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/awards': {
      id: '/admin/awards'
      path: '/awards'
      fullPath: '/admin/awards'
      preLoaderRoute: typeof AdminAwardsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAwardsRoute: typeof AdminAwardsRoute
  AdminCampsRoute: typeof AdminCampsRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEducationRoute: typeof AdminEducationRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPublicationsRoute: typeof AdminPublicationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAwardsRoute: AdminAwardsRoute,
  AdminCampsRoute: AdminCampsRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEducationRoute: AdminEducationRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPublicationsRoute: AdminPublicationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  AwardsRoute: AwardsRoute,
  CampsRoute: CampsRoute,
  CertificatesRoute: CertificatesRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  JourneyRoute: JourneyRoute,
  MediaRoute: MediaRoute,
  PrivacyRoute: PrivacyRoute,
  PublicationsRoute: PublicationsRoute,
  ResponsibilitiesRoute: ResponsibilitiesRoute,
  SkillsRoute: SkillsRoute,
  SocialWorkRoute: SocialWorkRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
